变量显示:
  无称号显示: "§c无称号"
  无VIP显示: "§c无VIP"
  无公会显示: " c无公会"
  无结婚显示: "§c单身"
  玩家权限:
    op: "§c[§e管理员§c]§f"
    player: "§c[§a玩家§c]§f"
  游戏模式:
    "0": "生存"
    "1": "创造"
    "2": "冒险"
    "3": "旁观"
  飞行:
    "0": "飞行开启"
    "1": "飞行关闭"

# 这里可以设置样式
# 默认为 default 和 easy
# 样式可以在 theme 文件夹添加
默认样式: default

自定义刷新刻度:
  底部: 20
  Boss血条: 20
  头部: 20
  计分板: 20
  聊天栏公告: 20
  motd: 20

自定义MOTD:
  是否启用: false
  内容: "&l{color}当前在线人数 {online}/{maxplayer}\n{version}"
自定义指令:
  name: tips
  aliases:
    - 底部
  description: 自定义玩家提示

